language: python

python:
    - "3.5"
    - "3.6"

sudo: false

addons:
  firefox: latest

before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver

env:
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=2.1

matrix:
    fast_finish: true
    include:
      - python: "3.7"
        dist: xenial
        env: DJANGO=2.0
      - python: "3.7"
        dist: xenial
        env: DJANGO=2.1

      - python: "3.4"
        env: DJANGO=1.11
      - python: "3.4"
        env: DJANGO=2.0

      - python: "2.7"
        env: DJANGO=1.11

      - python: "3.7"
        env: TOXENV="flake8"
      - python: "3.7"
        env: TOXENV="isort"

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
    email: false
