language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

sudo: false

addons:
  firefox: latest

env:
    matrix:
        - DJANGO=1.8
        - DJANGO=1.9
        - DJANGO=1.10
        - DJANGO=1.11
    global:
        - MOZ_HEADLESS=1

matrix:
    fast_finish: true
    include:
      - python: "3.6"
        env: DJANGO=1.11
      - python: "3.3"
        env: DJANGO=1.8
      - python: "2.7"
        env: TOXENV="flake8"
      - python: "2.7"
        env: TOXENV="isort"

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
    email: false
